"""Add video_clips table

Revision ID: 9e058dac8a7f
Revises: 6ce8940711e7
Create Date: 2025-12-07 04:47:01.764844

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9e058dac8a7f'
down_revision = '6ce8940711e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_clips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('clip_index', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('s3_bucket', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_clips_end_time'), 'video_clips', ['end_time'], unique=False)
    op.create_index(op.f('ix_video_clips_session_id'), 'video_clips', ['session_id'], unique=False)
    op.create_index('ix_video_clips_session_time', 'video_clips', ['session_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_video_clips_start_time'), 'video_clips', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_clips_start_time'), table_name='video_clips')
    op.drop_index('ix_video_clips_session_time', table_name='video_clips')
    op.drop_index(op.f('ix_video_clips_session_id'), table_name='video_clips')
    op.drop_index(op.f('ix_video_clips_end_time'), table_name='video_clips')
    op.drop_table('video_clips')
    # ### end Alembic commands ###
