"""Add thumbnail_s3_key to video_clips

Revision ID: f4c4b3a6d22e
Revises: 9e058dac8a7f
Create Date: 2025-12-07 05:35:51.137472

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f4c4b3a6d22e'
down_revision = '9e058dac8a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_clips', sa.Column('thumbnail_s3_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_clips', 'thumbnail_s3_key')
    # ### end Alembic commands ###
